---
id: JavascriptMinify_Jsmin
name: JavascriptMinify_Jsmin
full: |-
  JavaScript minification library - JSMin driver
description: >-
  The JSMin javascript minifier driver for use with the Horde_JavascriptMinify
  library.
list: dev
type: library
authors:
  - name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
version:
  release: 2.0.0
  api: 2.0.0alpha1
state:
  release: stable
  api: alpha
license:
  identifier: JSON
  uri: https://www.json.org/license.html
dependencies:
  required:
    php: ^7.4 || ^8
    composer:
      horde/javascriptminify: ^2
keywords: null
vendor: horde
ci-platform:
  '8.0':
    - php: ^8.1
    - ext-dom
  '8.1':
    - php: ^8.1
    - ext-dom
  '8.2':
    - php: ^8.1
    - ext-dom
  '8.3':
    - php: ^8.1
    - ext-dom
  '8.4':
    - php: ^8.1
    - ext-dom
  '8.5':
    - php: ^8.1
    - ext-dom
  '8.6':
    - php: ^8.1
    - ext-dom
ci-platform-flags:
  needs_installer_plugin: false
